<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-2NA4FFI8" failures="1" tests="1" name="Smoke_Test_inEdge" time="81.337" errors="0" timestamp="2022-07-26T08:24:38 IST">
  <testcase classname="MindQ.SeleniumTestngFrameworkJune.LoginTestCases" name="loginUsingInvalidCredentials" time="2.924">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Test case is failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Test case is failed expected [false] but found [true]
at MindQ.SeleniumTestngFrameworkJune.LoginTestCases.loginUsingInvalidCredentials(LoginTestCases.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginUsingInvalidCredentials -->
</testsuite> <!-- Smoke_Test_inEdge -->
